'use strict';
const $ = id => document.getElementById(id);
let token = '', activeRun = '', activeSelection = 'selection_initial', detail = null;
let state = null, page = 0, loadTicket = 0, busyRequest = false, polling = false;
let finishedJob = '', candidates = [];
const pageSize = 25;
const format = value => Number(value).toLocaleString('ja-JP');
const stageLabels = {queued:'処理を準備しています',loading:'データを確認しています',validated:'入力の確認が完了しました',embedding:'AbLang2で配列を数値化しています',kmeans:'K-meansで分類・スコア計算しています',umap:'3時点の共通UMAPを計算しています',density:'3時点の密度を計算しています',projection:'共通座標を確認しています',analysis_completed:'解析が完了し、画像を準備しています',projection_completed:'共通座標の計算が完了しました',rendering:'候補の位置を画像にしています',reselection:'候補を再選択しています',render:'候補の位置を画像にしています',completed:'完了しました',failed:'処理が停止しました',selection:'候補を再選択しています'};
function notice(message, error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=!message;}
async function api(url, data){const options={cache:'no-store',headers:{}};if(data!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-LMQASAS-Token':token};options.body=JSON.stringify(data);if(new TextEncoder().encode(options.body).byteLength>64*1024*1024)throw new Error('送信上限64 MiBを超えています。大きな入力ファイルは解説書のCLI手順で解析してください。');}const response=await fetch(url,options);let result;try{result=await response.json();}catch{throw new Error('サーバーから応答を読み取れませんでした。起動状態を確認してください。');}if(!response.ok)throw new Error(result.error||result.message||'処理できませんでした。入力と設定を確認してください。');return result;}
function fileUrl(path,download=false){return '/api/file?'+new URLSearchParams({run:activeRun,path,...(download?{download:'1'}:{})});}
function element(tag,text,cls){const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(cls)item.className=cls;return item;}
function localDate(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.valueOf())?value:d.toLocaleString('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function syncPresets(id){document.querySelectorAll(`[data-target="${id}"]`).forEach(button=>button.setAttribute('aria-pressed',String(Number(button.dataset.count)===Number($(id).value))));}
document.querySelectorAll('[data-count]').forEach(button=>button.addEventListener('click',()=>{$(button.dataset.target).value=button.dataset.count;syncPresets(button.dataset.target);}));
['newTopN','resultTopN'].forEach(id=>$(id).addEventListener('input',()=>syncPresets(id)));
for(const phase of ['pre','peak','post']){$(phase+'File').addEventListener('change',()=>{const file=$(phase+'File').files[0];$(phase+'Name').textContent=file?file.name:'CSV / Excelを選択';$(phase+'Name').title=file?file.name:'';$(phase+'File').closest('label').classList.toggle('selected',Boolean(file));});}
function setBusy(){const busy=busyRequest||Boolean(state?.job&&['queued','running'].includes(state.job.status));$('analyze').disabled=busy;$('reselect').disabled=busy||!detail;$('visualize').disabled=busy||!detail;$('selectionChoice').disabled=busy;$('resultTopN').disabled=busy;}
function showJob(job){if(!job){$('jobPanel').hidden=true;setBusy();return;}$('jobPanel').hidden=false;const running=['queued','running'].includes(job.status);$('jobTitle').textContent=job.status==='failed'?'処理を確認してください':job.status==='completed'?'処理が完了しました':job.type==='analyze'?'3時点を解析中':job.type==='reselect'?'候補数を変更中':'共通UMAPを作成中';const progress=job.progress;if(running&&typeof progress==='number'&&Number.isFinite(progress)){$('jobProgress').value=progress;$('jobPercent').textContent=Math.round(progress*100)+'%（現在の工程）';}else if(running){$('jobProgress').removeAttribute('value');$('jobPercent').textContent='処理中';}else{$('jobProgress').value=job.status==='completed'?1:0;$('jobPercent').textContent=job.status==='completed'?'完了':'';}$('jobMessage').textContent=job.error||stageLabels[job.stage]||(running?'計算中です。初回のUMAP準備には時間がかかることがあります。':'結果を確認できます。');const order=['validated','embedding','kmeans','umap','density','render','completed'];const normalized=({loading:'validated',analysis_completed:'kmeans',projection:'umap',projection_completed:'density',rendering:'render',reselection:'kmeans'})[job.stage]||job.stage;const index=order.indexOf(normalized);document.querySelectorAll('[data-stage]').forEach(node=>{const i=order.indexOf(node.dataset.stage);node.classList.toggle('active',running&&i===index);node.classList.toggle('done',job.status==='completed'||i<index);});setBusy();}
function renderRunList(runs){const old=$('runChoice').value;$('runChoice').replaceChildren(element('option',runs.length?'結果を選択…':'保存した結果はありません'));$('runChoice').options[0].value='';for(const run of runs){const option=element('option',`${run.subject||'解析結果'} · ${localDate(run.created_at)}${run.status!=='completed'?'（未完了）':''}`);option.value=run.id;option.disabled=run.status!=='completed';$('runChoice').append(option);}if(runs.some(r=>r.id===old))$('runChoice').value=old;}
async function poll(){if(polling)return;polling=true;try{state=await api('/api/state');renderRunList(state.runs||[]);showJob(state.job);if(state.job&&['completed','failed'].includes(state.job.status)&&finishedJob!==state.job.id){finishedJob=state.job.id;if(state.job.status==='completed'&&state.job.result?.run_id){await loadRun(state.job.result.run_id,state.job.result.selection_id||'selection_initial');notice('保存しました。候補一覧と画像を確認できます。');}else if(state.job.status==='failed')notice(state.job.error||'処理が停止しました。設定と入力を確認してください。',true);}if(!activeRun&&!busyRequest){const initial=(state.runs||[]).find(r=>r.status==='completed');if(initial)await loadRun(initial.id);}}catch(error){notice(error.message,true);}finally{polling=false;}}
async function loadRun(run,selection='selection_initial'){if(!run)return;const ticket=++loadTicket;activeRun=run;activeSelection=selection;detail=null;$('runChoice').value=run;$('plotFigure').hidden=true;$('figureActions').hidden=true;$('candidatePanel').hidden=true;$('auditPanel').hidden=true;$('metrics').hidden=true;$('plotEmpty').hidden=false;$('resultTitle').textContent='結果を読み込み中…';setBusy();try{const data=await api('/api/run?'+new URLSearchParams({run,selection}));if(ticket!==loadTicket)return;detail=data;activeSelection=data.selection.id;renderDetail();}catch(error){if(ticket===loadTicket){$('resultTitle').textContent='結果を確認できません';notice(error.message,true);}}finally{setBusy();}}
function renderDetail(){const meta=detail.metadata;$('resultTitle').textContent=meta.subject||'解析結果';$('runBadge').textContent='保存済みの解析';$('metrics').replaceChildren();for(const phase of ['Pre','Peak','Post']){const sample=detail.input_audit?.samples?.[phase];const card=element('div',undefined,'metric');card.append(element('div',phase,'metric-label'));const count=element('div',format(sample?.clone_count??0),'metric-number');count.append(element('small','clones'));card.append(count);$('metrics').append(card);}$('metrics').hidden=false;const selections=detail.selections||[];$('selectionChoice').replaceChildren();for(const item of selections){const option=element('option',`${format(item.summary.returned)}種類（指定 ${format(item.summary.requested)}）${item.id==='selection_initial'?' · 初回':' · '+item.id.slice(10)}`);option.value=item.id;$('selectionChoice').append(option);}$('selectionChoice').value=activeSelection;const summary=detail.selection.summary;$('resultTopN').value=summary.requested;syncPresets('resultTopN');$('candidateCount').textContent=format(summary.returned)+' 種類';const notes=[];if(summary.shortfall>0)notes.push(`指定 ${format(summary.requested)}種類に対し、候補は${format(summary.returned)}種類です。不足分を重複で補っていません。`);if(summary.boundary_tie)notes.push(`選択の境界に同点があります。同点内はCDR-H3の辞書順で選択しています。`);$('selectionNote').textContent=notes.join(' ');$('selectionNote').hidden=!notes.length;candidates=detail.candidates||[];page=0;$('search').value='';renderTable();$('csvDownload').href=fileUrl(activeSelection+'/candidates.csv',true);$('provenanceDownload').href=fileUrl(activeSelection+'/candidate_provenance.json',true);$('candidatePanel').hidden=false;const view=detail.latest_view;if(view?.path){const url=fileUrl(view.path);$('plot').src=url;$('plotLink').href=url;$('pngDownload').href=fileUrl(view.path,true);$('plotFigure').hidden=false;$('plotEmpty').hidden=true;$('figureActions').hidden=false;}else{$('plot').removeAttribute('src');$('plotFigure').hidden=true;$('plotEmpty').hidden=false;$('figureActions').hidden=true;$('plotEmpty').querySelector('h3').textContent='この選択結果の共通UMAPを表示';$('plotEmpty').querySelector('p').textContent='保存済みの数値表現から図を作ります。AbLang2とスコアの再計算は行いません。';}renderAudit();setBusy();}
function renderTable(){const query=$('search').value.trim().toUpperCase();const filtered=candidates.filter(r=>String(r.cdr3).includes(query));const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages-1);const start=page*pageSize,rows=filtered.slice(start,start+pageSize);$('candidateRows').replaceChildren();for(const row of rows){const tr=element('tr');tr.append(element('td',format(row.rank)),element('td',row.cdr3,'sequence'),element('td',Number(row.score).toLocaleString('ja-JP',{maximumFractionDigits:4}),'numeric'),element('td',format(row.clone_count),'numeric'),element('td',row.cluster_ids));$('candidateRows').append(tr);}if(!rows.length){const tr=element('tr');const td=element('td','一致する候補がありません。');td.colSpan=5;tr.append(td);$('candidateRows').append(tr);}$('tableRange').textContent=filtered.length?`${format(start+1)}–${format(Math.min(start+pageSize,filtered.length))} / ${format(filtered.length)}種類`:'0種類';$('pageLabel').textContent=`${page+1} / ${pages}`;$('prevPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;}
function renderAudit(){
  const node=$('auditContent');node.replaceChildren();
  const table=element('table'),head=element('tr');
  ['時点','入力形式','使用シート','入力行','採用行','除外行','clone数'].forEach(value=>head.append(element('th',value)));table.append(head);
  const formatLabels={cpm_csv:'CPM CSV',takara_xlsx:'タカラ／RG Excel',takara_rg_xlsx:'タカラ／RG Excel'};
  for(const phase of ['Pre','Peak','Post']){
    const s=detail.input_audit?.samples?.[phase]||{},tr=element('tr');
    [phase,formatLabels[s.input_format]||s.input_format,s.source_sheet,s.total_rows,s.accepted_rows,s.excluded_rows,s.clone_count].forEach(v=>tr.append(element('td',typeof v==='number'?format(v):v??'—')));table.append(tr);
  }
  const scroll=element('div',undefined,'table-scroll');scroll.append(table);node.append(scroll);
  for(const phase of ['Pre','Peak','Post']){
    const s=detail.input_audit?.samples?.[phase]||{},notes=[];
    if(s.input_policy==='takara-rg-hIGH20181210-v2-ignore-d')notes.push('Dコール・D機能ラベル：採否に使用しない');
    else if(s.input_policy==='takara-rg-hIGH20181210-v1')notes.push('旧条件：Dの注釈・機能も検査。この結果は旧条件のままです。新条件には3ファイルの新規解析が必要です');
    else if(s.input_format==='cpm_csv')notes.push('Dコール：入力に列なし・採否に使用しない');
    else if(s.input_format==='takara_rg_xlsx')notes.push('Dの採用条件：保存された記録で確認してください');
    if(s.isotype_granularity)notes.push('アイソタイプの粒度：'+(({subclass:'サブクラス',class:'クラス'})[s.isotype_granularity]||s.isotype_granularity));
    if(s.cdr3_definition)notes.push('CDR-H3の定義：'+(s.cdr3_definition==='as_reported_no_boundary_repair'?'入力の報告配列を使用（末端の補完なし）':s.cdr3_definition));
    if(notes.length)node.append(element('p',phase+' — '+notes.join(' / ')));
  }
  const p=detail.metadata.parameters||{};
  node.append(element('p',`解析条件：K=${p.n_clusters} / epsilon=${p.epsilon} / seed=${p.seed} / n_init=${p.n_init}。`));
  node.append(element('p','各時点のcloneを等重みで扱います。Countsは重みに使いません。epsilon、乱数条件、pooling、注釈のまとめ方などは、元論文との厳密な一致が未確認の暫定設定です。'));
  node.append(element('p','入力表だけでは全VDJの機能性や読み枠を独立に検証できません。候補の抗原特異性・中和能は、別途検証が必要です。'));
  node.append(element('p','原本の変更を防ぐため、解析結果は実行ごとの別フォルダーへ保存します。詳細な入力検査と条件はrun_metadata.json、input_audit.jsonに残ります。'));
  for(const name of ['run_metadata.json','input_audit.json']){const link=element('a',name+' を保存','text-link');link.href=fileUrl(name,true);link.setAttribute('download','');node.append(link,document.createTextNode('　'));}
  $('auditPanel').hidden=false;
}
async function submitJob(url,payload){busyRequest=true;setBusy();notice('処理を受け付けています…');try{const result=await api(url,payload);state={...(state||{}),job:result.job};showJob(result.job);notice('処理を開始しました。進捗はこの画面で確認できます。');await poll();}catch(error){notice(error.message,true);}finally{busyRequest=false;setBusy();}}
function positiveInt(id){const n=Number($(id).value);if(!Number.isSafeInteger(n)||n<1)throw new Error('件数・計算条件は1以上の整数を指定してください。');return n;}
async function readFile(id){const f=$(id).files[0];if(!f||!(/\.(csv|xlsx)$/i).test(f.name))throw new Error('Pre・Peak・PostのCSV / Excelをそれぞれ選択してください。');if(f.size>20*1024*1024)throw new Error('入力は1ファイル20 MiB以下にしてください。');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('入力ファイルを読み取れませんでした。'));reader.onload=()=>resolve({name:f.name,base64:String(reader.result).split(',')[1]});reader.readAsDataURL(f);});}
$('analysisForm').addEventListener('submit',async event=>{event.preventDefault();if($('analyze').disabled)return;try{busyRequest=true;setBusy();const files=await Promise.all(['preFile','peakFile','postFile'].map(readFile));if(new Set(files.map(file=>file.name.split('.').pop().toLowerCase())).size!==1)throw new Error('3時点は同じ入力形式でそろえてください。CSVとExcelは混在できません。');const payload={subject:$('subject').value.trim(),top_n:positiveInt('newTopN'),n_clusters:positiveInt('clusters'),epsilon:Number($('epsilon').value),seed:Number($('seed').value),n_init:positiveInt('nInit'),batch_size:positiveInt('batchSize'),threads:positiveInt('threads'),files:{Pre:files[0],Peak:files[1],Post:files[2]}};await submitJob('/api/analyze',payload);}catch(error){notice(error.message,true);}finally{busyRequest=false;setBusy();}});
$('reselect').addEventListener('click',()=>{try{const payload={run_id:activeRun,top_n:positiveInt('resultTopN')};if(detail?.projections?.length)payload.projection_id=detail.projections[0].id;submitJob('/api/reselect',payload);}catch(error){notice(error.message,true);}});
$('visualize').addEventListener('click',()=>submitJob('/api/visualize',{run_id:activeRun,selection_id:activeSelection}));
$('runChoice').addEventListener('change',event=>loadRun(event.target.value));$('selectionChoice').addEventListener('change',event=>loadRun(activeRun,event.target.value));$('refresh').addEventListener('click',poll);$('search').addEventListener('input',()=>{page=0;renderTable();});$('prevPage').addEventListener('click',()=>{page--;renderTable();});$('nextPage').addEventListener('click',()=>{page++;renderTable();});
async function init(){try{token=(await api('/api/bootstrap')).token;await poll();setInterval(poll,3000);}catch(error){notice('起動したローカルサーバーに接続できません。起動ウィンドウを確認してページを再読み込みしてください。',true);}}
init();
